version: 2.1
orbs:
  node: circleci/node@5.0.3
  docker: circleci/docker@2.1.4
  terraform: circleci/terraform@3.1

jobs:
  build_next:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: echo building!!!
          name: Nada
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test_next:
    executor: node/default
    steps:
      - run:
          command: |
            echo "Testing NextJS..."
  terrorformize:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    environment:
        TF_VAR_awsKey: $AWS_ACCESS_KEY
        TF_VAR_awsSecret: $AWS_ACCESS_KEY
        TF_VAR_dockerPwd: $DOCKER_LOGIN
        TF_VAR_dockerUsername: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: terraform init
          command: | 
            terraform init -backend-config="access_key=$AWS_ACCESS_KEY" -backend-config="secret_key=$AWS_SECRET"
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
      - run:
          name: terraform apply
          command: |
            terraform apply -auto-approve -replace=aws_instance.jakl-web-auto
#          requires:
#            - terraform/plan

workflows:
  containerize_deploy:
    jobs:
      - docker/publish:
          executor:
            image: circleci/node
            name: docker/docker
            tag: boron-browsers
          image: aklaimd/jakl-ui
          remote-docker-dlc: true
          tag: latest
          use-remote-docker: true
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          deploy: true
          # filters:
          #   branches:
          #     only:
          #       - main
      - terrorformize:
          # filters:
          #   branches:
          #     only:
          #       - main
          requires:
            - docker/publish